### ISSUE TITLE
scheduled sampling in PredCNN

### ISSUE THREAD

**Issue by elmanvon** [xzr12/PredCNN#3]
Hi @xzr12, thanks for great work. I have a few questions:

1.  What is the **scheduled sampling** used in PredCNN codebase? Why use it?

2. Why in the code you are trying to divide a single image into 16 blocks via the hparam called ``patch_size``, which is set to 4 by default? Will that destroy global shape information?

Appreciate if you could provide some answers.

**Comment by xzr12** [comment]
1. Schedule sampling is used to predict multiple frames in a sequential way. It's not adopted when dealing with problems for next-frame prediction.
2. The parameter patch_size is just set as other works did and it's a hyper-parameter. It may destroy global information since we just predict part of the image, but it can improve the efficiency a great deal.
